language: c
os:
  - linux
compiler:
  - gcc
script: make clean && make && make tarball
env:
  global:
    - MAKEFLAGS="-j 2"
matrix:

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-get install -y
    build-essential autoconf autoconf2.64
    automake autopoint bison build-essential ca-certificates
    debootstrap e2fslibs-dev ed fakechroot gettext git
    libdbus-1-3 libgdbm-dev libkeyutils-dev libssl-dev
    libblkid-dev libtool-bin liburcu-dev pkg-config qemu-utils uuid-dev
    rsync symlinks lsb-release zlib1g-dev golang-1.8-go ;
    fi
